### ISSUE TITLE
It's showing errors when running the project

### ISSUE THREAD

**Issue by albertpike** [atornel/RestaurantAppUIKit#2]
Pub get, Pub upgrade, Get dependencies
It's all done.

Did I miss something?

**flutter doctor -v**
`C:\Users\USER.DESKTOP-DN21MBP>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\scr\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\USER.DESKTOP-DN21MBP\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\USER.DESKTOP-DN21MBP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!`

**Console log after running:**
`Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
lib/screens/walkthrough.dart:31:11: Error: No named parameter with the name 'dotsDecorator'.
          dotsDecorator: DotsDecorator(
          ^^^^^^^^^^^^^
/C:/scr/flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-1.0.8/lib/src/model/page_decoration.dart:51:9: Context: Found this candidate, but the arguments don't match.
  const PageDecoration({
        ^^^^^^^^^^^^^^
lib/screens/walkthrough.dart:15:20: Error: Too many positional arguments: 0 allowed, but 2 found.
Try removing the extra positional arguments.
      PageViewModel(
                   ^
/C:/scr/flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-1.0.8/lib/src/model/page_view_model.dart:28:3: Context: Found this candidate, but the arguments don't match.
  PageViewModel({
  ^^^^^^^^^^^^^
lib/screens/walkthrough.dart:55:11: Error: No named parameter with the name 'dotsDecorator'.
          dotsDecorator: DotsDecorator(
          ^^^^^^^^^^^^^
/C:/scr/flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-1.0.8/lib/src/model/page_decoration.dart:51:9: Context: Found this candidate, but the arguments don't match.
  const PageDecoration({
        ^^^^^^^^^^^^^^
lib/screens/walkthrough.dart:39:20: Error: Too many positional arguments: 0 allowed, but 2 found.
Try removing the extra positional arguments.
      PageViewModel(
                   ^
/C:/scr/flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-1.0.8/lib/src/model/page_view_model.dart:28:3: Context: Found this candidate, but the arguments don't match.
  PageViewModel({
  ^^^^^^^^^^^^^
lib/screens/walkthrough.dart:79:11: Error: No named parameter with the name 'dotsDecorator'.
          dotsDecorator: DotsDecorator(
          ^^^^^^^^^^^^^
/C:/scr/flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-1.0.8/lib/src/model/page_decoration.dart:51:9: Context: Found this candidate, but the arguments don't match.
  const PageDecoration({
        ^^^^^^^^^^^^^^
lib/screens/walkthrough.dart:63:20: Error: Too many positional arguments: 0 allowed, but 2 found.
Try removing the extra positional arguments.
      PageViewModel(
                   ^
/C:/scr/flutter/.pub-cache/hosted/pub.dartlang.org/introduction_screen-1.0.8/lib/src/model/page_view_model.dart:28:3: Context: Found this candidate, but the arguments don't match.
  PageViewModel({
  ^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\scr\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\scr\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Picked up _JAVA_OPTIONS: -Xmx512m
Finished with error: Gradle task assembleDebug failed with exit code 1`

**Comment by JideGuru** [comment]
Thanks for reporting the issue @albertpike
We will look into it and get back to you

**Comment by JideGuru** [comment]
@albertpike The introduction_screen plugin got updated with new ways of using it.
I'll update the code

**Comment by albertpike** [comment]
> @albertpike The introduction_screen plugin got updated with new ways of using it.
> I'll update the code

Thank you for your fast reply, @JideGuru 
Noted! That would be highly appreciated.

**Comment by JideGuru** [comment]
@albertpike I made an update, test if that fixes the issue

**Comment by albertpike** [comment]
It worked!

Thank you @JideGuru
